name: test
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rules
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: test
        run: "jq --version"
        env:
          RULES_WEBHOOK_URL: ${{ secrets.RULES_WEBHOOK_URL }}
