# This is a basic workflow to help you get started with Actions

name: updateRules

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    paths:
      - '/rules/raw/**'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  updateWebhook:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rules
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out the repository to the runner
        uses: actions/checkout@v4

      - name: Discord Webhook Action
      # You may pin to the exact commit or the version.
      # uses: tsickert/discord-webhook@b217a69502f52803de774ded2b1ab7c282e99645
        uses: tsickert/discord-webhook@v7.0.0
        with:
          # Webhook URL from discord. See: https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks for details
          webhook-url: https://discord.com/api/webhooks/1238624258255622325/gLZFxw1n4ettEVzLCPTKnNZy4oNuugsoN7kEFCV38TT29SZE304PJxlaPMNz0aretUOt
          # Message that is sent via the webhook.
          content: test
      
      - name: Run webhook message updater script
        run: ./updateWebhook.sh
